### PR TITLE
fix README

### PR DESCRIPTION
**Pull request by ToruMakabe**
Correct usage passing environment variables

### CODE REVIEW

**Comment by Lawouach** [comment]
Hi @ToruMakabe 

Thanks for this, I think it makes sense because these values are mostly read from the environment. But, the original README could have been interepreted as "these values are hardcoded in the experiment". Maybe, the change should reflect they can be both, not one over the other?

Mind you, if the most common use case is via environment variable, maybe it makes sense to default our doc to this?

cc @bugra-derre

**Comment by ToruMakabe** [comment]
Hi @Lawouach 

Is "the original README" you mentioned the following page?
https://docs.chaostoolkit.org/drivers/azure/

If so, I think the change should reflect both docs and would be default. Because the way is "recommended" and in terms of security.

Thanks

**Comment by Lawouach** [comment]
I should have been clearer, by original I meant "before your change". Good news, the page you refer is a copy of the readme in this repo (but only updated on each release of the extension)

**Comment by ToruMakabe** [comment]
@Lawouach Thank you for your explanation. 

There are two ways of handling secret on this doc, using environment variables and hardcoding. In my understanding, these are independent. My PR is only for the case of using environment variables. The original code does not work, so the purpose of this PR is to fix it.

Could you tell me if I make a misunderstanding?  Thanks!

**Comment by Lawouach** [comment]
It does indeed. Sorry if I confused you.

**Pull request merged**
