### PR TITLE
Add Azure Database for PostgreSQL actions

### PR DESCRIPTION
**Pull request by Lunik**
-  Introduce actions for Azure Database for PostgreSQL flexible, like starting, stoping, restarting and deleting servers
-  Introduce actions for Azure Database for PostgreSQL singlge, like restarting and deleting servers

Signed-off-by: Lunik <lunik@tiwabbit.fr>

### CODE REVIEW

**Comment by Lunik** [comment]
@Lawouach could you or another reviewer take a look at this PR ?

**Comment by Lawouach** [comment]
Gosh, sorry/ Yes let me look.

**Comment by xpdable** [comment]
> Gosh, sorry/ Yes let me look.

@Lawouach plz see my review, need to change the Client init with a scope due to MS sdk chages.

**Comment by Lawouach** [comment]
> > Gosh, sorry/ Yes let me look.
> 
> @Lawouach plz see my review, need to change the Client init with a scope due to MS sdk chages.

Indeed. I'll add it directly myself.

**Pull request merged**
