### PR TITLE
Add Azure Application Gateway actions

### PR DESCRIPTION
**Pull request by jbblache**
Introduce actions for Azure Application Gateway, like starting, stopping, deleting application gateways and deleting routes

Signed-off-by: jbblache <jbaptiste.blache@gmail.com>

### CODE REVIEW

**Comment by jbblache** [comment]
Hello @Lawouach, could you have a look at this PR ?

**Review by Lawouach — APPROVED** [review]
Very good stuff!

**Comment by Lawouach** [comment]
@jbblache if you could fix the syntax so the linter is happy, then i'll merge quite happily.

**Comment by Lawouach** [comment]
Thanks @jbblache it's merged :)

**Pull request merged**
