### PR TITLE
Introduce actions for Azure Web Apps

### PR DESCRIPTION
**Pull request by buderre**
Provide actions to stop, restart and start Azure Web Apps.

Resolves: #46
Signed-off-by: Derre, Bugra (415) <bugra.derre@daimler.com>

### CODE REVIEW

**Comment by Lawouach** [comment]
Hey @buderre,

Thanks again for the PR! :)
It claims you have conflicts however. Could you have a look before I review please? :)

**Comment by buderre** [comment]
@Lawouach : Done. Thanks for the hint. Did not see the conflicts at all.

**Comment by Lawouach** [comment]
Interesting. You did merge commit instead of a rebase right? 

Quick question, I see you have a delete_webapp action. I assume there is no way to recover from that, right?

Also, any reason why no probes for getting a list of apps?

**Comment by buderre** [comment]
@Lawouach : You are right :) We will do it in a new branch this week. I will close this PR and put a new one instead.

**Pull request closed without merging**
