### PR TITLE
Add ability to stress virtual machine scale set instances

### PR DESCRIPTION
**Pull request by maximmold**

### CODE REVIEW

**Comment by maximmold** [comment]
This PR could definitely use some DRY principle cleanup, but it should be a good starting point.

**Comment by Lawouach** [comment]
Would it be possibel to squash it for a first review please?

**Comment by xpdable** [comment]
quick question with no check. Would machine actions still work if all script folder is moved?
https://github.com/chaostoolkit-incubator/chaostoolkit-azure/blob/dcab325b70fd8ec84176a644314c32710fb804d7/chaosazure/machine/actions.py#L233

**Comment by buderre** [comment]
> quick question with no check. Would machine actions still work if all script folder is moved?
> https://github.com/chaostoolkit-incubator/chaostoolkit-azure/blob/dcab325b70fd8ec84176a644314c32710fb804d7/chaosazure/machine/actions.py#L233

No. The scripts need to be included in the MANIFEST.in file. Else it won't work. @maximmold I like the approach to make it more local. Can you please test the bundled package locally and test whether it works or not?

**Comment by maximmold** [comment]
Sorry. That was definitely my intention to go back and update the machine package to point to the new directory, but I forgot to do it.

**Comment by maximmold** [comment]
Ahha! I'm used to an editor with autosave mode and did not save the actions file under the machines package.

**Comment by Lawouach** [comment]
Hey @maximmold I'm assuming the last commit is part of the other you pushed initially. Could you squash them all and force push by any chance?

**Comment by maximmold** [comment]
I tested the stop_machines action with the changes above and it still worked.

**Comment by buderre** [comment]
@maximmold Can you update the CHANGELOG.md with your changes to document the changes for other users?

**Comment by maximmold** [comment]
I'll try to hit this up next week.

**Comment by maximmold** [comment]
Should be good now.

**Comment by Lawouach** [comment]
Well yes and now. Now, I don't fully understand what your changes do. The first commit is a merge commit and the last one removes the init_client function. I don't quite understand what this PR does now.

Are you on the slack at https://join.chaostoolkit.org/ by any chance? I hate to being a pain but maybe we should get on a quick chat there so I fully grasp the two PRs :)

**Pull request closed without merging**
