### PR TITLE
Feature/64 burn io

### PR DESCRIPTION
**Pull request by LucasHolzmann**
Introduce a new feature stressing the I/O operations per second of the hard drive for Linux. Windows is not supported yet. Works by copying random data into a burn folder, which is deleted at the end of the script.

### CODE REVIEW

**Comment by Lawouach** [comment]
Hi @LucasHolzmann, I think merging the previous PR triggered a conflict in this one. Would you be able to rebase your own branch from master please?

**Comment by LucasHolzmann** [comment]
Hi @Lawouach, I did a git pull --rebase from the latest master: result was "Everything is up to date". Any ideas ?

**Comment by Lawouach** [comment]
Hi @LucasHolzmann, this is really odd indeed. When I look here, I can see differences. I'll have a look.

**Comment by Lawouach** [comment]
Alright, on your branch, I did this:

```
$ git clone https://github.com/DaimlerTSS/chaostoolkit-azure.git
$ git checkout feature/64-burn-io
$ git pull --rebase git@github.com:chaostoolkit-incubator/chaostoolkit-azure.git master
From github.com:chaostoolkit-incubator/chaostoolkit-azure
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Introduce new feature: burn I/O
```

It seems it pulled the master into it as expected. Odd this didn't work on your side :)

**Comment by LucasHolzmann** [comment]
@Lawouach Look. Like Magic :) It works now

**Comment by Lawouach** [comment]
Hah! Awesome :)

**Pull request merged**
