### PR TITLE
Enable fine-granular filter queries for virtual machines

### PR DESCRIPTION
**Pull request by seriousscorpion**
Instead of providing resource groups in the configuration file, the user
is now able to provide filter queries. The filter queries are passed
locally to the action. With this solution the user is able to use a
fine-granular filter.

Requirement: The resource-graph extension is a pre-requirement. The
application will install the resource-graph extension if is not
installed.

Resolves: #21
Signed-off-by: Auli Rahnasto <auli.rahnasto@gmx.de>

### CODE REVIEW

**Comment by Lawouach** [comment]
That's a little deeper than I'm familiar with the platform here :p 

I assume your change is not backward compatible, right? 

Also, would you say, being able to set configuration on a per activity basis have helped? https://github.com/chaostoolkit/chaostoolkit-lib/issues/32

I'm wondering if your changes falls into "configuration" vs "arguments". Mind sharing your thoughts?

**Comment by seriousscorpion** [comment]
Of course.

1. You are right. From an API perspective: this change is not backwards compatible. From a project overall goal perspective: this change enables the user to filter for his Azure resources, in this case virtual machines that belong to a specific resource group or have a specific id or name. In the end an user benefits from the filter opportunity.

2. I would say No. Passing the resource group as a config parameter is rather unfortunate designed. When you look at the AWS extension (https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/master/chaosaws/ec2/actions.py) you will see a filter mechanism directly in the action. Filter the machines that you need with a custom filter query.

I hope I am able to describe the benefit here. Feel free for questions.

**Comment by Lawouach** [comment]
Indeed, that makes sense. Fortunately, I don't think we have many users of this extension yet. Let's ping @bugra-derre who is using it. To prevent too many surprises :)

**Comment by seriousscorpion** [comment]
That looks good to me -> useful

**Comment by bugra-derre** [comment]
I agree. It seems good :)

**Pull request merged**
